#!/usr/bin/env python

import os
import pyrax
import argparse




# Main function
def main():

  # Parse the command line arguments
  parser = argparse.ArgumentParser(description="Work with cloud files and directories", prog='challenge3')
  parser.add_argument('--fqdn', help='fully qualified domain name', required=True)
  parser.add_argument('--ip', help='ip address', required=True)
  args = parser.parse_args()


  # Authenticate using a credentials file: "~/.rackspace_cloud_credentials"
  cred_file = "%s/.rackspace_cloud_credentials"  % (os.environ['HOME'])
  print "Setting authentication file to %s" % (cred_file)
  pyrax.set_credential_file(cred_file)

  # Instantiate a clouddns object
  print "Instantiating cloud_dns object"
  cdnsobj = pyrax.cloud_dns


  # Make a decision based on action
  domains = cdnsobj.list()
  for domain in domains:
    if args.fqdn.endswith(domain.name):
      print "Found a matching domain: " + domain.name + " for fqdn: " + args.fqdn
      recs = [{'type': 'A', 'name': args.fqdn, 'data':args.ip, 'ttl':6000}]
      print "Adding record: \n\t" + args.fqdn + "   IN  A  " + args.ip
      cdnsobj.add_records(domain, recs)



# Called on execution. We are going to call the main() function
if __name__ == "__main__":
  main()
